export const data = [
  {
    question: "What is the command to create a new React app?",
    option1: "npx create-react-app my-app",
    option2: "npm start-react-app my-app",
    option3: "npx start-react-app my-app",
    option4: "npm create-react-app my-app",
    ans: 1,
  },
  {
    question: "Which of the following is a lifecycle method in React?",
    option1: "componentWillMount",
    option2: "onComponentUpdate",
    option3: "beforeRender",
    option4: "initComponent",
    ans: 1,
  },
  {
    question: "How do you pass data from parent to child component in React?",
    option1: "using refs",
    option2: "using state",
    option3: "using props",
    option4: "using context",
    ans: 3,
  },
  {
    question: "What hook is used to manage state in a functional component?",
    option1: "useContext",
    option2: "useState",
    option3: "useReducer",
    option4: "useEffect",
    ans: 2,
  },
  {
    question: "Which of the following is used for handling side effects in React?",
    option1: "useEffect",
    option2: "useReducer",
    option3: "useContext",
    option4: "useState",
    ans: 1,
  },
  {
    question: "What is JSX?",
    option1: "A JavaScript syntax extension",
    option2: "A CSS preprocessor",
    option3: "A type of HTML",
    option4: "A React component",
    ans: 1,
  },
];
